#!/bin/sh

buildIt()
{
   mkdir -p build
   javac -d build src/truthtablegenerator/*.java
}

jarIt()
{
  jar cfe ttg.jar truthtablegenerator.GUI -C build . -C src resources
}

makeOneJar()
{
   if test -f ttg.jar
   then
      cp $HOME/Library/Java/Extensions/JMathTeX-0.7pre.jar build
      cp $HOME/Library/Java/Extensions/jdom-1.1.3.jar build
      (cd build; jar xf JMathTeX-0.7pre.jar; jar xf jdom-1.1.3.jar)
      jar uf ttg.jar -C build be -C build org
      rm build/JMathTeX-0.7pre.jar
      rm build/jdom-1.1.3.jar
   fi
}

runIt()
{
   java -jar ttg.jar
}

if test -f ttg.jar
then
   makeOneJar
   runIt
else
   buildIt
   jarIt
   runIt
fi
